# Generated by Django 6.1 on 2026-08-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Versão')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('mileage', models.IntegerField(verbose_name='Quilometragem (km)')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Base (€)')),
                ('origin_country', models.CharField(max_length=50, verbose_name='País de Origem')),
                ('fuel_type', models.CharField(max_length=30, verbose_name='Combustível')),
                ('co2_emissions', models.IntegerField(default=150, verbose_name='Emissões CO2 (g/km)')),
                ('market_type', models.CharField(choices=[('ORIGIN', 'Mercado de Origem (Alemanha, EAU, etc.)'), ('SPAIN', 'Mercado de Destino (Espanha)')], default='ORIGIN', max_length=10)),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='URL do Anúncio')),
            ],
        ),
        migrations.CreateModel(
            name='ImportCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_fee', models.DecimalField(decimal_places=2, default=485.0, max_digits=8, verbose_name='Taxa de Leilão (€)')),
                ('buyer_fees', models.DecimalField(decimal_places=2, default=430.0, max_digits=8, verbose_name='Honorários (€)')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=826.0, max_digits=8, verbose_name='Transporte (€)')),
                ('homologation_cost', models.DecimalField(decimal_places=2, default=60.0, max_digits=8, verbose_name='Ficha Reduzida (€)')),
                ('itv_cost', models.DecimalField(decimal_places=2, default=141.32, max_digits=8, verbose_name='ITV (€)')),
                ('target_margin', models.DecimalField(decimal_places=2, default=2000.0, max_digits=8, verbose_name='Margem Madcars (€)')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='calculadora.vehicle')),
            ],
        ),
    ]
