# Generated by Django 6.1 on 2026-08-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='source_url',
        ),
    ]
