# Generated by Django 6.1 on 2026-08-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_remove_vehicle_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte / Vendedor'),
        ),
    ]
