# Generated by Django 6.1 on 2026-08-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_vehicle_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática')], default='Automática', max_length=50, verbose_name='Transmissão'),
        ),
    ]
