# Generated by Django 6.1 on 2026-08-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_vehicle_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], default='Diesel', max_length=30, verbose_name='Combustível'),
        ),
    ]
