# Generated by Django 6.1 on 2026-08-30 15:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0005_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcalculation',
            name='documentation_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='importcalculation',
            name='gestoria_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='auction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('485.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='buyer_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('430.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='homologation_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='itv_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('141.32'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='target_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('826.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_calculation', to='calculadora.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='co2_emissions',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], default='Gasolina', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='market_type',
            field=models.CharField(choices=[('SPAIN', 'Comparável (Espanha)'), ('ORIGIN', 'Carro p/ Importar (Origem)')], default='SPAIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='origin_country',
            field=models.CharField(default='Espanha', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller',
            field=models.CharField(blank=True, default='Particular', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automática', 'Automática'), ('Manual', 'Manual')], default='Automática', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(),
        ),
    ]
