# Generated by Django 6.1 on 2026-08-30 18:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0006_importcalculation_documentation_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importcalculation',
            options={'verbose_name': 'Cálculo de Importação', 'verbose_name_plural': 'Cálculos de Importação'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='auction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('485.00'), max_digits=10, verbose_name='Taxa de Leilão (€)'),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='buyer_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('430.00'), max_digits=10, verbose_name='Honorários Comprador (€)'),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='documentation_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=10, verbose_name='Custo Documentação (€)'),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='gestoria_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10, verbose_name='Custo Gestoria (€)'),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='homologation_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10, verbose_name='Custo Homologação (€)'),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='itv_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('141.32'), max_digits=10, verbose_name='Custo ITV (€)'),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='target_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10, verbose_name='Margem Alvo (€)'),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('826.00'), max_digits=10, verbose_name='Custo Transporte (€)'),
        ),
        migrations.AlterField(
            model_name='importcalculation',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_calculation', to='calculadora.vehicle', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='co2_emissions',
            field=models.IntegerField(default=120, verbose_name='Emissões CO₂ (g/km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='currency',
            field=models.CharField(default='EUR', max_length=10, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_size',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cilindrada'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], default='Gasolina', max_length=20, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='market_type',
            field=models.CharField(choices=[('SPAIN', 'Comparável (Espanha)'), ('ORIGIN', 'Carro p/ Importar (Origem)')], default='SPAIN', max_length=10, verbose_name='Tipo de Mercado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(verbose_name='Quilometragem (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='origin_country',
            field=models.CharField(default='Espanha', max_length=100, verbose_name='País de Origem'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='power',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Potência (cv)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço de Compra'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller',
            field=models.CharField(blank=True, default='Particular', max_length=255, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source_url',
            field=models.URLField(blank=True, default='', verbose_name='URL do Anúncio'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automática', 'Automática'), ('Manual', 'Manual')], default='Automática', max_length=20, verbose_name='Transmissão'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='version',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(verbose_name='Ano'),
        ),
    ]
